name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@test-ga
      - runs:
        using: 'docker'
        image: 'Dockerfile'